Immunization_session
LUKEINTERNATIONAL/MAHIS pull request #359
Opened 2024-09-19 12:47 UTC by KellsWorks

2024-09-19 13:39 UTC, Senzenjani approved these changes

2024-09-20 08:02 UTC, fchiyenda requested changes
Hello Kelvin the scheduling options are not working properly as discussed let us implement a pure scheduler with explicit options

2024-10-01 08:10 UTC, Senzenjani approved these changes
### Improvements to be done
- Weekly should only be visible if different start and end date is less or equal to 7
- Repeat type to be on top of start and end date selection
- Calendar to allow single day select if repeat type is daily and never
- update placeholder and required on frequency on repeat type select
- Add the selection of specific days in a week

2024-10-02 13:48 UTC, fchiyenda approved these changes

2024-10-02 13:49 UTC, merged